minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - '@iconify-json/lucide@1.2.140'
  - '@iconify-json/simple-icons@1.2.99'
  - pino-pretty@13.2.0
  - viem@2.57.3

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1

shellEmulator: true

overrides:
  '@noble/hashes': 1.8.0
  h3: 1.15.11

allowBuilds:
  '@parcel/watcher': true
  '@posthog/cli': true
  bufferutil: true
  core-js: true
  es5-ext: true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
  vue-demi: true
