name: Post-Deployment Actions for PRs
on:
  check_run:
    types: [completed]
jobs:
  post-deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.check_run.check_suite.pull_requests[*].url, 'pull') # Ensures it runs for PRs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Deployment URL
        run: |
          echo "DEPLOYMENT_URL=$(echo "${{ github.event.check_run.output.summary }}" | grep -o "href=.*>https" | cut -c 7-43)" >> $GITHUB_ENV
      - name: Run Post-Deployment Actions
        run: |
          echo "Deployment URL: $DEPLOYMENT_URL"
